# Generated by Django 4.2.4 on 2023-11-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
