# Generated by Django 4.2.4 on 2023-11-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_remove_userconsent_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
