# Generated by Django 4.2.4 on 2023-11-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userconsent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
