# Generated by Django 4.2.4 on 2023-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userconsent_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='can_be_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='can_data_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
